# Generated by Django 2.2.4 on 2020-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonBelt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='Destination',
            new_name='destination',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.AlterField(
            model_name='wish',
            name='travelEnd',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wish',
            name='travelStart',
            field=models.DateField(),
        ),
    ]
