# Generated by Django 2.2.4 on 2020-10-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PythonBelt_app', '0002_auto_20201020_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptionUploaded', to='PythonBelt_app.User'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='travelEnd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='travelStart',
            field=models.DateField(null=True),
        ),
    ]
