# Generated by Django 2.2.4 on 2020-10-21 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PythonBelt_app', '0003_auto_20201020_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='travelEnd',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='travelStart',
            field=models.DateField(),
        ),
    ]
